--- #YAML:1.0
name:                Lemonldap-NG-Common
version:             0.9
abstract:            Common files for Lemonldap::NG infrastructure
license:             ~
author:              
    - guimard <guimard@>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Cache::Cache:                  0
    CGI:                           3.08
    DBI:                           0
    Regexp::Assemble:              0
    Storable:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
