--- #YAML:1.0
name:               Lemonldap-NG-Common
version:            1.1.2
abstract:           Common files for Lemonldap::NG infrastructure
author:
    - Xavier Guimard <x.guimard@free.fr>, Clément Oudot <clement@oodo.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    IO::String:  0
requires:
    Cache::Cache:      0
    CGI:               3.08
    Config::IniFiles:  0
    Crypt::Rijndael:   0
    DBI:               0
    HTTP::Headers:     0
    IO::String:        0
    Regexp::Assemble:  0
    SOAP::Lite:        0
    Storable:          0
    XML::Simple:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
