---
abstract: 'Common files for Lemonldap::NG infrastructure'
author:
  - 'Xavier Guimard <x.guimard@free.fr>, Clément Oudot <clement@oodo.net>'
build_requires:
  IO::String: '0'
  Net::LDAP: '0'
  Test::Pod: '1'
  XML::Simple: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lemonldap-NG-Common
no_index:
  directory:
    - t
    - inc
recommends:
  Apache::Session::Browseable: '0'
  HTML::Template: '0'
  HTTP::Message: '0'
  Net::LDAP: '0'
  XML::LibXML: '0'
  XML::Simple: '0'
requires:
  Apache::Session: '0'
  CGI: '3.08'
  Cache::Cache: '0'
  Config::IniFiles: '0'
  Crypt::OpenSSL::RSA: '0'
  Crypt::OpenSSL::X509: '0'
  Crypt::Rijndael: '0'
  DBI: '0'
  Digest::SHA: '0'
  File::Basename: '0'
  Mouse: '0'
  Net::CIDR::Lite: '0'
  SOAP::Lite: '0'
  Storable: '0'
version: v1.4.3
