--- #YAML:1.0
name:               Lemonldap-NG-Common
version:            1.3.2
abstract:           Common files for Lemonldap::NG infrastructure
author:
    - Xavier Guimard <x.guimard@free.fr>, Clément Oudot <clement@oodo.net>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    IO::String:   0
    Net::LDAP:    0
    Test::Pod:    1
    XML::Simple:  0
requires:
    Apache::Session:      0
    Cache::Cache:         0
    CGI:                  3.08
    Config::IniFiles:     0
    Crypt::OpenSSL::RSA:  0
    Crypt::OpenSSL::X509:  0
    Crypt::Rijndael:      0
    DBI:                  0
    File::Basename:       0
    Net::CIDR::Lite:      0
    SOAP::Lite:           0
    Storable:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    Apache::Session::Browseable:  0
    HTML::Template:       0
    HTTP::Message:        0
    Net::LDAP:            0
    XML::LibXML:          0
    XML::Simple:          0
